### ISSUE TITLE
'locale' config option is not optional

### ISSUE THREAD

**Issue by bredmor** [InteractionDesignFoundation/nova-unlayer-field#6] opened 2020-05-07 15:18 UTC
The README says this option is optional, however failing to specify it causes a javascript error from `vendor.js` - `locale is not defined`.

**Comment by phuclh** [comment] 2021-03-03 23:06
I have the same issue.

**Comment by lptn** [comment] 2021-03-04 09:03
@bredmor 
@phuclh 
I couldn't reproduce it unfortunately. Can you please share a minimal config that causes this error?

**Comment by lptn** [comment] 2021-03-04 11:05
should be fixed within version [0.2.2](https://github.com/InteractionDesignFoundation/nova-unlayer-field/releases/tag/0.2.2)

**Closed by lptn** 2021-03-04 11:05 UTC
